### ISSUE TITLE
[Feature Request] Support template compilation

### ISSUE THREAD

**Issue by posva** [znck/rollup-plugin-vue#14]
Hello.
In Vue 2 it's possible to compile template to render functions. I gave it a try but got stuck trying to get rid of  strict mode (template compilation uses `with`). My work is [here](https://github.com/posva/rollup-plugin-vue/commit/9f5dd9f9126f8fa6303565a0dd93840f0ea354a7). It's far from being enough for a PR but it shows how easy it is to compile to a render function.

It'd be great to provide an option like `compileTemplate` that defaults to false.

I'm willing to keep working on this and add the feature (with tests and doc) but I really need some help, I don't know rollup much. This is the config I was testing with:

``` js
const rollup = require('rollup').rollup
const node = require('rollup-plugin-node-resolve')
const cjs = require('rollup-plugin-commonjs')
const vue = require('rollup-plugin-vue')
const buble = require('rollup-plugin-buble')
const replace = require('rollup-plugin-replace')
const fs = require('fs')

rollup({
  entry: 'test/unit/specs/Hello.spec.js',
  plugins: [
    replace({
      'process.env.VUE_ENV': "'browser'"
    }),
    vue({css: false}),
    node(),
    cjs(),
    buble({ safe: false })
  ]
})
  .then(function (bundle) {
    var code = bundle.generate({
      format: 'iife',
      sourceMap: 'inline',
      useStrict: false
    }).code
    return write('dist/papier.test.js', code).then(function () {
      return code
    })
  })
  .catch(logError)

function write (dest, code) {
  return new Promise(function (resolve, reject) {
    fs.writeFile(dest, code, function (err) {
      if (err) return reject(err)
      console.log(blue(dest) + ' ' + getSize(code))
      resolve()
    })
  })
}

function getSize (code) {
  return (code.length / 1024).toFixed(2) + 'kb'
}

function logError (e) {
  console.log(e)
}

function blue (str) {
  return '\x1b[1m\x1b[34m' + str + '\x1b[39m\x1b[22m'
}
```

**Comment by znck** [comment]
That would be great. I think for Vue 2+, it should compile template as render function and for earlier versions, current approach would be enough.

A configuration like `compileTemplate` would be good to allow little flexibility.

👍 @posva

**Comment by posva** [comment]
@znck Just found a __forked__ repo that supports the with statement. It uses a little hack: https://github.com/thgh/rollup-plugin-vue2/blob/master/src/index.js#L28-L33
But I don't think there's another option

**Comment by posva** [comment]
@znck Got it working here: https://github.com/znck/rollup-plugin-vue/compare/master...posva:vue-compile-template

**Comment by znck** [comment]
`ongenerate` is a rollup hook. It is called when the bundle is generated.

`with` statements: compiled template uses `with(this)` statement, the approach to replace `with(this)` with `if('__VUE_WITH_STATEMENT__')` after template is compiled and reverting it back to `with(this)` when bundle is generated would work. (`vueify` or `vue-loader` uses same approach)

Let's complete the functionality first. Send a working PR, then tests and docs.

**Comment by posva** [comment]
@znck Thanks! I'll do a PR this evening.

How do you check the Vue version during the rollup process? Or are we just going to release a different version?

Allowing to disable the compilation of templates is important IMO for testing. I couldn't get around it. Most of the work for that is done

**Comment by znck** [comment]
`Vue.version`

**Comment by posva** [comment]
@znck Sorry to bother you more but that doesn't work. Is there something else I have to add to make that statement work? Otherwise, I can just keep the config option false by default

**Comment by znck** [comment]
For now, lets keep the config option `false` by default.

**Comment by truesilver92** [comment]
Which option is this to make `rollup-plugin-vue` compile the templates to render functions? I had to switch to `rollup-plugin-vue2`, but the project claims that it isn't maintained.
