### ISSUE TITLE
error 'does not export default' when use this plugin

### ISSUE THREAD

**Issue by zjhiphop** [znck/rollup-plugin-vue#2]
I created a test case in rollup play ground, and it works fine.
http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20quote%20from%20%20'module_1.js'%22%7D%2C%7B%22name%22%3A%22module_1.js%22%2C%22code%22%3A%22import%20QuoteService%20from%20'module_2.js'%5Cnexport%20default%20%7B%5Cn%20%20%20%20name%3A%20%5C%22Quote%5C%22%2C%5Cn%5Cn%20%20%20%20data%3A%20function()%7B%5Cn%20%20%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20%20%20quote%3A%20%5C%22%5C%22%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20ready%3A%20function()%20%7B%5Cn%20%20%20%20%20%20var%20quote%20%20%3D%20QuoteService.getQuote(this).quote%5Cn%20%20%20%20%20%20this.%24set('quote'%2C%20quote)%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%22%7D%2C%7B%22name%22%3A%22module_2.js%22%2C%22code%22%3A%22export%20default%20%7B%5Cn%20%20getQuote(ctx)%7B%5Cn%20%20%20%20%2F%2F%20Here%20you%20would%20make%20a%20request%20to%20your%20server%5Cn%5Cn%20%20%20%20%2F%2F%20return%20ctx.%24http.get('http%3A%2F%2Fyourserver.com%2Fapi'%2C%20function%20(data%2C%20status%2C%20request)%20%7B%5Cn%20%20%20%20%2F%2F%20%20%20%20%20%20%20return%20data%3B%5Cn%20%20%20%20%2F%2F%20%20%20%7D).error(function%20(data%2C%20status%2C%20request)%20%7B%5Cn%20%20%20%20%2F%2F%20%20%20%20%20%20%20return%20data%3B%5Cn%20%20%20%20%2F%2F%20%20%20%7D)%5Cn%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20quote%3A%20%5C%22Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%20adipisicing%20elit%2C%20sed%20do%20eiusmod%20tempor%20incididunt%20ut%5C%22%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%7D%5D%7D

**Comment by rodzzlessa24** [comment]
I'm getting the same error

**Comment by znck** [comment]
It uses `vueify` to transform `.vue` files to `.js`

**Comment by rodzzlessa24** [comment]
@znck Sounds good do you need help with anything?

**Comment by znck** [comment]
Yes, I do need help. You can start with trans-compiler for coffescript similar to babel.
current api:
```js
/**
 * @param {string} code
 * @param {Compiler} compiler
 * @param {string} filePath
* @returns {{code: string, map: {mappings: string}, type: string}} - type value should be 'script' or 'template' or 'style'
compile(code, compiler, filePath)
```

Second I need your opinion on the approach of injecting template in default export. Is there some other way to inject template in script?
```js
// Vueify does it like this. But it won't work with Rollup.
';(typeof module.exports === "function"' +
          '? module.exports.options' +
          ': module.exports).template = ' + JSON.stringify(template) + '\n'
```

**Comment by lukasjuhas** [comment]
Hey @znck,

Thanks for the plugin. 

Now, what do you mean by basic .vue files? Do you have any example?

Thanks!

**Comment by znck** [comment]
By basic `.vue` files, I mean`.vue` files without `style` section. There is no standard way of rolling up styles and there is an open issue for same (#7). I would implement something by mid-October.

> Sorry for taking this long. I am very occupied these days.
