### ISSUE TITLE
Not all dependencies have fixed version

### ISSUE THREAD

**Issue by szwacz** [znck/rollup-plugin-vue#31]
Hello, in `package.json` of this project there are few dependencies with `latest` version range. Is this intentional? Because from my experience this means problems waiting to happen.

**Comment by znck** [comment]
Fixed in [v2.2.7](https://github.com/znck/rollup-plugin-vue/tree/v2.2.7)!

👍

**Comment by znck** [comment]
Also included `yarn.lock` file.

**Comment by szwacz** [comment]
Thanks for blazingly fast action :)
