### ISSUE TITLE
<slot> cannot appear inside <table>

### ISSUE THREAD

**Issue by rstoenescu** [znck/rollup-plugin-vue#40]
Following warning should not exist when dealing with Vue 2 in certain scenarios:

`Tag <slot> cannot appear inside <table> due to HTML content restrictions. It will be hoisted out of <table> by the browser.`

I think there should be a way to disable this warning.

Awesome work with this plugin! Keep up the good job!

**Comment by znck** [comment]
@rstoenescu Can you share reproduction code?
