### ISSUE TITLE
Error "writeFile is not defined" (Vue 2, yarn, Node 7.2.1)

### ISSUE THREAD

**Issue by congrady** [znck/rollup-plugin-vue#41]
Hello,

I'm getting this error when trying to run rollup in development mode:
writeFile is not defined
...at compileStyle (..../node_modules/rollup-plugin-vue/dist/rollup-plugin-vue.common.js:258:9)

rollupConfig: https://gist.github.com/congrady/1797c706c0229d65826842028756bb45
package.json: https://gist.github.com/congrady/611f2fc76c8adb389e201f0163c6f52f

Os X El Captain

running with "yarn run dev"

Anyone can help? Thanks a lot!

**Comment by znck** [comment]
Bug introduced by v2.2.11

Fixed in v2.2.13


Please upgrade `rollup-plugin-vue`
