### ISSUE TITLE
JSX Transform

### ISSUE THREAD

**Issue by miljan-aleksic** [znck/rollup-plugin-vue#51]
Thank you @znck, this plugin is very much needed!

After the error `ReferenceError: React is not defined` and LOL I can confirm the plugin doesn't support JSX transformation and somehow uses the React one. I can even see in yarn.lock the react references, although is not a direct dependency.

I am not sure about the solution, relatively new to Rollup and bundlers plugins, but would like to help in any matter possible, so let me know!

**Comment by znck** [comment]
Can provide your rollup config file and the file (or part ) that is causing the error?

**Comment by miljan-aleksic** [comment]
It's a migration in progress, so please ignore all the noise - [Rollup config](https://github.com/vuikit/vuikit/blob/rollup_issue/rollup.config.js), [JSX example](https://github.com/vuikit/vuikit/blob/rollup_issue/lib/Table/columns/core.js#L11).

**Comment by miljan-aleksic** [comment]
I have converted the JSX code into pure functions and the react issue is gone, but some still persist. 

```
[Vue warn]: Error when rendering component <transition>: 
[Vue warn]: Unknown custom element: <tabcontent>
```

Transition is a global component and tabcontent (functional) is locally declared.

**Comment by znck** [comment]
`rollup-plugin-vue` works with `.vue` files only. For JSx there is [babel-plugin-transform-vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx).

**Comment by miljan-aleksic** [comment]
I know, I'm talking about .vue files with JSX code inside, which is converted to js with `babel-plugin-transform-vue-jsx`. Anyway, even without JSX code, seems failing with functional components.

Did you tried those?

**Comment by znck** [comment]
I haven't. I'm trying now.

**Comment by posva** [comment]
@miljan-aleksic You seem to be passing a babel options object to buble at https://github.com/vuikit/vuikit/blob/rollup_issue/rollup.config.js#L20
You can use the [rollup-plugin-jsx](https://github.com/konsumer/rollup-plugin-jsx) to handle that as in https://github.com/posva/vue-plugin-template/blob/master/template/build/build.js#L44

**Comment by miljan-aleksic** [comment]
@posva, interesting. How is that for Webpack Evan has created a Vue specific plugin but for Rollup this generic one is enough?

**Comment by posva** [comment]
@miljan-aleksic You may miss some very specific features: https://github.com/vuejs/babel-plugin-transform-vue-jsx#jsx-spread. But using babel instead of buble is perfectly fine

**Comment by miljan-aleksic** [comment]
ok, thanks :)

**Comment by znck** [comment]
Check out this [example repository](https://github.com/znck/example-functional-rollup-plugin-vue). It got it working.

**Comment by miljan-aleksic** [comment]
I am currently refactoring the library and when finish will get pack to the build. You are both awesome, thank you guys!

**Comment by houd1ni** [comment]
@posva  Any updates of vue-jsx with rollup? I've got a similar issue: https://github.com/vuejs/rollup-plugin-vue/issues/278

Seems that `@vue/babel-preset-jsx` isn't picked up by the plugin.

**Comment by realRoyHsu** [comment]
> Check out this [example repository](https://github.com/znck/example-functional-rollup-plugin-vue). It got it working.

![image](https://user-images.githubusercontent.com/33602954/68824263-3b3ce700-06d1-11ea-9493-f1ecd69f0956.png)

I run your example, compile error
