### ISSUE TITLE
<slot> cannot appear inside <table>

### ISSUE THREAD

**Issue by rstoenescu** [znck/rollup-plugin-vue#55]
### Expected behavior
Should not give warning.

### Actual behavior
Gives warnings:

```bash
 Warning in src/vue-components/data-table/DataTable.vue:
 
  58 | 
  59 |     <div v-else class="q-data-table-container" @mousewheel="mouseWheel" @DOMMouseScroll="mouseWheel">
    |                                                                         ^
  60 |       <div v-if="hasHeader" class="q-data-table-head" ref="head" :style="{marginRight: scroll.vert}">

  Found camelCase attribute: @DOMMouseScroll="mouseWheel". HTML is case-insensitive. Use @dommouse-scroll="mouseWheel" instead. Vue will automatically interpret it as camelCase in JavaScript. If this is an SVG camelCase attribute, use the .camel modifier.


 Warning in src/vue-components/data-table/plugins/sticky-cols/TableSticky.vue:
 
  27 |     <tbody v-if="!head">
  28 |       <slot></slot>
    |       ^
  29 |     </tbody>

  Tag <slot> cannot appear inside <table> due to HTML content restrictions. It will be hoisted out of <table> by the browser.


 Warning in src/vue-components/data-table/TableContent.vue:
 
  26 |     <tbody v-else>
  27 |       <slot></slot>
    |       ^
  28 |     </tbody>

  Tag <slot> cannot appear inside <table> due to HTML content restrictions. It will be hoisted out of <table> by the browser.
```

### Steps to reproduce the behavior
* Clone Quasar Framework repo (https://github.com/quasarframework/quasar)
* NPM install
* Run `npm run build js simple`

This has been fixed in previous versions but upgrading to `"rollup": "^0.41.4"` and `"rollup-plugin-vue": "2.2.18"` brings back the problem.

Awesome work with this plugin. When I have some money I will donate for it. Any links for this? Thanks!

**Comment by znck** [comment]
Before compiling, templates are validated using [vue-template-validator](https://github.com/vuejs/vue-template-validator). These warnings does effect the compilation processes. 

IMO `<slot>` in `<table>` when compiled to render function does not have any side effects. If you can confirm that I can suppress these warnings when `compileTemplate` is set to `true`.
    
    
---------
> I'm experimenting with docs & design of the repository and website. 😃  Suggestions are welcome.
>
> And thanks a lot supporting the plugin. I was planning to add a donation link after I have satisfactory docs. 😁  Though here is the donation link: https://www.paypal.me/znck

**Comment by rstoenescu** [comment]
Done. And thank you for the quick turnaround!

**Comment by znck** [comment]
😃  Thanks
