### ISSUE TITLE
How to rollup Vue component with styles?

### ISSUE THREAD

**Issue by znck** [znck/rollup-plugin-vue#7]
It can be done in one these ways:
- Export compiled CSS as `vendor.common.css`
- Export compiled SCSS as `vendor.common.scss`
- Inject CSS in JS

I choose 2nd.

Any other suggestions?

**Comment by victorwpbastos** [comment]
Would be great as an option.

**Comment by zce** [comment]
+1

**Comment by thgh** [comment]
Here is a proposal to change the behaviour for CSS based on an option:

```
vue({
  // Pass a filename to write all styles to
  css: 'bundle.scss',

  // Pass a function that will be called ongenerate with an array of style nodes as argument
  css (styleNodes) {
    writeFileSync(cssPath, styleNodes.map(n => n.content).join())
  }

  // Default behaviour is to write all styles to options.dest of the bundle
  // where .js is replaced by .css
  css: null,
})
```

**Comment by znck** [comment]
@thgh Continue implementing this. This would work.

If a project uses mix of style langs than it would not work. But that is acceptable (for now).
