### ISSUE TITLE
Please remove babel dependency

### ISSUE THREAD

**Issue by victorwpbastos** [znck/rollup-plugin-vue#8]
I think would be better if the user can choose to use or not babel. Maybe the user wants to use buble (my case) and have to install all the babel dependencies (that is huge).

**Comment by znck** [comment]
Babel is used to trans-compile ES6 source internally. 

I guess it can be made optional.

**Comment by victorwpbastos** [comment]
It would be great!

**Comment by znck** [comment]
Babel is removed. Now use some plugin to transpile ES6. See #10 .
